Adição do Modelo e API REST de Local
ProjetaoMUS/bike-parking-backend pull request #3
Opened 2023-09-09 22:57 UTC by hlaff147

Modelo Local: Criei um novo modelo chamado Local, que inclui campos para nome, número de vagas, imagens, localização, descrição, preço, latitude e longitude.

API REST para Local: Configurei um conjunto de visualizações baseadas no ModelViewSet para criar, recuperar, atualizar e deletar instâncias de Local. A API utiliza o Django Rest Framework e fornece todos os CRUDs padrão para o modelo Local.

Serialização: Implementei um serializer para o modelo Local para garantir a correta conversão entre instâncias do modelo e representações JSON.

Urls: Integrei as URLs do DRF com o roteamento padrão do Django para garantir um acesso sem problemas aos endpoints da API.

Upload de Imagens: Configurei o campo de imagens para aceitar uploads e armazenar arquivos em 'media/local/imagens/'. Adicionalmente, modifiquei o modelo para permitir a criação ou atualização de um Local mesmo sem fornecer uma imagem.

2023-09-09 23:06 UTC, gqmv requested changes

2023-09-09 23:06 UTC, gqmv commented on src/bike_parking/settings.py
> +import os
Import desnecessário

2023-09-09 23:06 UTC, gqmv commented on src/bike_parking/settings.py
> +MEDIA_ROOT = os.path.join(BASE_DIR, 'media/')
Usar path lib ao invés de os.path.join

2023-09-09 23:06 UTC, gqmv commented on src/local/models.py
Alterar nomes de variáveis e nome do modelo para ingles, seguindo o padrão do resto do código
PartnerLocation
name
parking_spaces_count
images
address
price
latitude
longitude

2023-09-09 23:06 UTC, gqmv commented on src/local/views.py
Usar esse vieste aqui permitiria que um usuario fizesse um post para o endpoint e alterasse os dados dos locais. é necessário usar uma solução que seja read only

2023-09-10 00:43 UTC, gqmv approved these changes

2023-09-10 00:43 UTC, gqmv commented
LGTM!

2023-09-10 00:44 UTC, sergiolbarreto approved these changes

2023-09-10 00:44 UTC, merged